apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: labelsettings.crds.example.com
spec:
  group: crds.example.com
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            requiredLabels:
              type: array
              maxItems: 128
              x-kubernetes-list-type: map
              x-kubernetes-list-map-keys:
              - name
              items:
                type: object
                required:
                - name
                properties:
                  name:
                    type: string
                    maxLength: 512
                  allowedValues:
                    type: array
                    maxItems: 128
                    items:
                      type: string
                      maxLength: 512
                    x-kubernetes-validations:
                    - message: "Values may be added to allowedValues but not removed"
                      rule: "oldSelf.all(v, v in self)"
  scope: Cluster
  names:
    plural: labelsettings
    singular: labelsetting
    kind: LabelSetting
