apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-prod-namespaces
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["*"]
- apiGroups: ["authz.example.com"]
  resources: ["production-namespaces"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manage-prod-namespaces-binding
  namespace: default
subjects:
- kind: User
  name: alice
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: manage-prod-namespaces
  apiGroup: rbac.authorization.k8s.io
